<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="rajendra-PC" name="BankingApp" tests="3" failures="2" timestamp="14 Sep 2017 06:45:16 GMT" time="23.588" errors="0">
  <testcase name="loginAsBankManager" time="0.319" classname="BankingApp.BankManagerLoginTest">
    <failure type="java.lang.AssertionError" message="Bank Manager login not successful">
      <![CDATA[java.lang.AssertionError: Bank Manager login not successful
	at BankingApp.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:18)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- loginAsBankManager -->
  <testcase name="addCustomer" time="8.659" classname="BankingApp.AddCustomerDetails">
    <failure type="java.lang.AssertionError" message="Add customer not successful">
      <![CDATA[java.lang.AssertionError: Add customer not successful
	at BankingApp.AddCustomerDetails.addCustomer(AddCustomerDetails.java:33)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase name="openAccount" time="13.791" classname="BankingApp.OpenBankAccount"/>
</testsuite> <!-- BankingApp -->
